sonar.projectKey=secure-banking-transaction-portal
sonar.projectName=Secure Banking Transaction Portal
sonar.projectVersion=1.0

sonar.sources=app
sonar.python.version=3.12

sonar.sourceEncoding=UTF-8

sonar.exclusions=venv/**,__pycache__/**,instance/**

sonar.coverage.exclusions=templates/**,static/**
